name: Run Backend Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Compile Backend Application
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Compile application
        run: |
          cd backend
          mvn clean compile

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Run unit tests
        run: |
          cd backend
          mvn clean test